---
title: "Plot POC flux"
author: "Thelma Panaïotis"
format:
  html:
    toc: true
    toc-depth: 3
    embed-resources: true
editor: visual
lightbox: true
execute:
  cache: true
  warning: false
---

```{r set_up}
#| output: false
#| cache: false
source("utils.R")
```

## Load data

```{r load}
df_poc_flux <- read_csv("data/00.df_poc_flux.csv", show_col_types = FALSE)
```

## Plot intensity of POC flux

```{r plot_intensity}
#| fig-column: body-outset
#| out-width: 100%

ggplot(df_poc_flux) +
  geom_density(aes(x = poc_flux, colour = source)) +
  labs(
    x = "POC flux (mg C m<sup>-2</sup> d<sup>-1</sup>)", 
    y = "Density", colour = "Source"
  ) +
  theme_classic() +
  facet_wrap(
    ~depth, ncol = 2, scales = "free", 
    labeller = labeller(depth = function(x) paste0(x, " m"))
  ) + 
  theme(
    axis.title.x = element_markdown(),
    strip.background = element_blank()
  )
```

## Plot with latitude

#### With points

```{r plot_lat_points}
#| fig-column: body-outset
#| out-width: 100%

ggplot(df_poc_flux, aes(x = poc_flux, y = lat, colour = source)) +
  geom_point(size = 0.3, alpha = 0.1) +
  geom_smooth(se = FALSE, orientation = "y") +
    facet_wrap(
    ~depth, scales = "free", 
    labeller = labeller(depth = function(x) paste0(x, " m"))
  ) +
  labs(
    x = "POC flux (mg C m<sup>-2</sup> d<sup>-1</sup>)", 
    y = "Latitude", colour = "Source"
  ) +
  theme_classic() + 
  theme(
    axis.title.x = element_markdown(),
    strip.background = element_blank()
  )
```

#### Without points

```{r plot_lat}
#| fig-column: body-outset
#| out-width: 100%

ggplot(df_poc_flux, aes(x = poc_flux, y = lat, colour = source)) +
  geom_smooth(se = FALSE, orientation = "y") +
    facet_wrap(
    ~depth, scales = "free", 
    labeller = labeller(depth = function(x) paste0(x, " m"))
  ) +
  labs(
    x = "POC flux (mg C m<sup>-2</sup> d<sup>-1</sup>)", 
    y = "Latitude", colour = "Source"
  ) +
  theme_classic() + 
  theme(
    axis.title.x = element_markdown(),
    strip.background = element_blank()
  )
```
